spring.application.name=ApiGateway


server.port=8080

eureka.client.service-url.default-zone=http://localhost:8761/eureka/






spring.boot.admin.client.url=http://localhost:1111


spring.boot.admin.client.instance.service-host-type=IP




management.endpoints.web.exposure.include=*

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true





#gateway



# Gateway route
#customer
spring.cloud.gateway.server.webmvc.routes[0].id=Customer-Service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:1241
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/customer/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# Swagger
springdoc.swagger-ui.urls[0].name=Customer Service
springdoc.swagger-ui.urls[0].url=/customer/v3/api-docs




# Gateway route
#paymnt
spring.cloud.gateway.server.webmvc.routes[1].id=Paymnt-Service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:1239
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/paymnt/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

# Swagger
springdoc.swagger-ui.urls[1].name=Paymnt Service
springdoc.swagger-ui.urls[1].url=/paymnt/v3/api-docs



# Gateway route
#Booking
spring.cloud.gateway.server.webmvc.routes[2].id=Booking-Service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:1237
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/booking/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

# Swagger
springdoc.swagger-ui.urls[2].name=Booking Service
springdoc.swagger-ui.urls[2].url=/booking/v3/api-docs

