spring.application.name=Config-server
server.port=1245

# Config Server - Git repository
spring.cloud.config.server.git.uri=https://github.com/shivampal108/microservices-config-repo

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=*

# Spring Boot Admin
spring.boot.admin.client.url=http://localhost:1111


spring.boot.admin.client.instance.service-host-type=IP